// Positions of the Elements on Display


// -----------------------------------------

// Elements in All View (excl. offset)

// -----------------------------------------

#define ONE_SCALE_NAME_FONT Arial_14
#define ONE_SCALE_NAME_X 15
#define ONE_SCALE_NAME_Y 5

#define ONE_SCALE_KG_FONT Arial_12
#define ONE_SCALE_KG_X 15
#define ONE_SCALE_KG_Y 55
#define ONE_SCALE_KG_SUFFIX " kg"

#define ONE_SCALE_KG_RECT_X ONE_SCALE_KG_X
#define ONE_SCALE_KG_RECT_Y ONE_SCALE_KG_Y
#define ONE_SCALE_KG_RECT_W 120-ONE_SCALE_KG_X-1
#define ONE_SCALE_KG_RECT_H 50

#define ONE_SCALE_CAL_FONT Arial_12
#define ONE_SCALE_CAL_X 15
#define ONE_SCALE_CAL_Y 105
#define ONE_SCALE_CAL_SUFFIX " C"

#define ONE_SCALE_CAL_RECT_X ONE_SCALE_CAL_X
#define ONE_SCALE_CAL_RECT_Y ONE_SCALE_CAL_Y
#define ONE_SCALE_CAL_RECT_W 120-ONE_SCALE_CAL_X-1
#define ONE_SCALE_CAL_RECT_H 50


// -----------------------------------------

// Elements in Menu

// -----------------------------------------


#define MENU_BUTTON_FONT Arial_10

#define BUTTON_BACK_WRITING "Ich will hier weg"
#define BUTTON_BACK_WRITING_X 70
#define BUTTON_BACK_WRITING_Y 15

#define BUTTON_DOWN_WRITING "F-Down"
#define BUTTON_DOWN_WRITING_X 3
#define BUTTON_DOWN_WRITING_Y 206

#define BUTTON_UP_WRITING "F-Up"
#define BUTTON_UP_WRITING_X 123
#define BUTTON_UP_WRITING_Y 206

#define BUTTON_MINUS_WRITING "C -"
#define BUTTON_MINUS_WRITING_X 3
#define BUTTON_MINUS_WRITING_Y 246

#define BUTTON_PLUS_WRITING "C +"
#define BUTTON_PLUS_WRITING_X 123
#define BUTTON_PLUS_WRITING_Y 246

#define BUTTON_RESET_WRITING "Reset"
#define BUTTON_RESET_WRITING_X 3
#define BUTTON_RESET_WRITING_Y 286

#define BUTTON_TARE_WRITING "Tare"
#define BUTTON_TARE_WRITING_X 123
#define BUTTON_TARE_WRITING_Y 286

#define MENU_NAME_DISPLAY_X 10
#define MENU_NAME_DISPLAY_Y 50
#define MENU_NAME_DISPLAY_FONT Arial_12

#define MENU_KG_DISPLAY_X 10
#define MENU_KG_DISPLAY_Y 90
#define MENU_KG_DISPLAY_FONT Arial_14
#define MENU_KG_DISPLAY_PREFIX "Gewicht: "
#define MENU_KG_DISPLAY_SUFFIX " kg"

#define MENU_KG_DISPLAY_RECT_X MENU_KG_DISPLAY_X
#define MENU_KG_DISPLAY_RECT_Y MENU_KG_DISPLAY_Y
#define MENU_KG_DISPLAY_RECT_W 240-MENU_KG_DISPLAY_RECT_X-1
#define MENU_KG_DISPLAY_RECT_H 40

#define MENU_CAL_DISPLAY_X 10
#define MENU_CAL_DISPLAY_Y 130
#define MENU_CAL_DISPLAY_FONT Arial_12
#define MENU_CAL_DISPLAY_PREFIX "C: "
#define MENU_CAL_DISPLAY_SUFFIX " C"

#define MENU_CAL_DISPLAY_RECT_X MENU_CAL_DISPLAY_X
#define MENU_CAL_DISPLAY_RECT_Y MENU_CAL_DISPLAY_Y
#define MENU_CAL_DISPLAY_RECT_W 240-MENU_CAL_DISPLAY_RECT_X-1
#define MENU_CAL_DISPLAY_RECT_H 30

#define MENU_CALF_DISPLAY_X 10
#define MENU_CALF_DISPLAY_Y 160
#define MENU_CALF_DISPLAY_FONT Arial_12
#define MENU_CALF_DISPLAY_PREFIX "CF: "
#define MENU_CALF_DISPLAY_SUFFIX " %"

#define MENU_CALF_DISPLAY_RECT_X MENU_CALF_DISPLAY_X
#define MENU_CALF_DISPLAY_RECT_Y MENU_CALF_DISPLAY_Y
#define MENU_CALF_DISPLAY_RECT_W 240-MENU_CALF_DISPLAY_RECT_X-1
#define MENU_CALF_DISPLAY_RECT_H 30